[/Users/jab/src/git/hub/jab3/src/bash/keyboard/t.sh, /Users/jab/src/git/hub/jab3/src/bash/keyboard/v.sh,
  /Users/jab/src/git/hub/jab3/src/bash/keyboard/w.sh, /Users/jab/src/git/hub/jab3/src/bash/keyboard/z.sh,
  /Users/jab/src/git/hub/jab3/src/bash/git/__init__.sh, /Users/jab/src/git/hub/jab3/src/bash/git/completion.sh,
  /Users/jab/src/git/hub/jab3/src/bash/git/functons.sh, /Users/jab/src/git/hub/jab3/bin/first_dir.sh,
  /Users/jab/src/git/hub/jab3/environ.d/colour.sh, /Users/jab/src/git/hub/jab3/src/bash/keyboard/r.sh,
  /Users/jab/src/git/hub/jab3/src/bash/git/statuses.sh, /Users/jab/src/git/hub/jab3/src/bash/zzz_renames.sh,
  /Users/jab/.virtualenvs/whyp/bin/activate, /Users/jab/src/git/hub/jab3/src/bash/functons.sh,
  /Users/jab/src/git/hub/jab3/src/bash/python.sh, /Users/jab/src/git/hub/jab3/src/bash/welcome.sh]
