dist: xenial
language: python
python:
- '3.7'
install: pip install tox
script: tox
notifications:
  email: false
  slack:
    secure: E08/tj137DR78xUMTAkI7HjnR6VrnZN+rTxOccKJGawkKkQRu6ZGi1ZxZ3ph8CDIG2Zin8vDURMiZByhOjoC3eKFyUJ/3zJGN+Ql9YD9QI3W4DCmRJZvcDGANGzZaX5lsoMsVMyxzMsSPWPKCbr0/HOWWNjqrFhgmX3bQIUn1zA=
deploy:
  provider: pypi
  user: jalanb
  on:
    tags: true
  password:
    secure: htrmSc8NXrv480DBwcuJ/lXxZRaDkyoezqP9CCuCb2o6F19LfOJGPinak98vW/F3P5+HbxACpH23l1eT3ueXLvytJJrolS8v7VrELeEqkeHLbMAf1gwLoDfa3sTAezr3R2vA3sET95eGKTRLi51J+bLr7G2JLp5A5p5Ku5BJcCc=
